// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPMXXulxU_LmQLQRbEPAbf4FSEFRNcHKk',
    appId: '1:391790546224:web:269492e54e1eb4b638ccf5',
    messagingSenderId: '391790546224',
    projectId: 'deposit-app-qa',
    authDomain: 'deposit-app-qa.firebaseapp.com',
    storageBucket: 'deposit-app-qa.appspot.com',
    measurementId: 'G-T5NH5WJTH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3eswCsp_k0YT0BtDrXFBrcyQnsrt-go',
    appId: '1:391790546224:android:e3a698bd0684baea38ccf5',
    messagingSenderId: '391790546224',
    projectId: 'deposit-app-qa',
    storageBucket: 'deposit-app-qa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Qu3MWAREkKs6g57f_H08uHcTfENg1Oo',
    appId: '1:391790546224:ios:457438f182191b1e38ccf5',
    messagingSenderId: '391790546224',
    projectId: 'deposit-app-qa',
    storageBucket: 'deposit-app-qa.appspot.com',
    iosClientId: '391790546224-51qec0ktd79pme9g41ti1kca72loa19b.apps.googleusercontent.com',
    iosBundleId: 'io.empowerchain.depositapp',
  );
}
